### ISSUE TITLE
[Feature] Import data from csv

### ISSUE THREAD

**Issue by Omranic** [rinvex/cortex-foundation#44]

**Comment by noxify** [comment]
Do you mean something like this
* https://github.com/Maatwebsite/Laravel-Excel / http://www.maatwebsite.nl/laravel-excel/docs
* http://itsolutionstuff.com/post/laravel-5-import-export-to-excel-and-csv-using-maatwebsite-exampleexample.html

**Comment by Omranic** [comment]
Yes, `maatwebsite/excel` planned to be used. It's easy task, but consume some time to implement across all modules. Export features already implemented. I'd love if someone can take over this task to be honest ❤️

**Comment by noxify** [comment]
My idea to implement the importer is the following:

We have in the adminarea one generic entry point, which handles the uploading of the CSV files.
In the view we have the following fields available:

* Required - File field: Will be used to allow an user to choose a file to upload
* Required - Dropdown field: Will be used to allow an user to choose which importer should be used
* Optional - Text field: Will be used to allow an user to overwrite the `delimiter`
* Optional - Text field: Will be used to allow an user to overwrite the `enclosure`
* Optional - Text field: Will be used to allow an user to overwrite the `line_ending`
* Required - Button: Will be used to start the import


After pressing the button, we will call a method in the generic importer controller.
Based on the selected importer, will we call the referenced Class to start creating the records.

We have for the available importer a new config file.
The structure is something like that:

```

<?php 

return [

	'users' => \Cortex\Foundation\Importer\UserListImport::class,
	'roles'	=> \Cortex\Foundation\Importer\RoleListImport::class,,
	'products' => \Cortex\Foundation\Importer\ProductListImport::class,

];

```

With is, we have a extendable solution for the future.
Also, we're using the out of the box functionality from the maatwebsite/excel package.
The implementating here calls automagically a Handler with the same name.

Example: UserListImport calls UserListImportHandler

In the handler we have a `handle` function. Here we can process all rows and have also the possibility to create some custom stuff e.g. Assign a User to a role based on the given value.


But i'm unsure about the execution...

In the example, we have the following controller:

```
class ExampleController extends Controller {

    public function importUserList(UserListImport $import)
    {
        // Handle the import
        $import->handleImport();
    }

}
```

But we need something like this:

```
class ExampleController extends Controller {

    public function importUserList(Request $request)
    {
    	$importList = config('cortex::importer.'.$request->importer);
    	$import = new $importList($request);
        // Handle the import
        $import->handleImport();
    }

}
```

We have to check it, if it's possible.


if someone has another idea how to import it, please let me know :)
Discussions, feedback etc. are very welcome :)

**Comment by Omranic** [comment]
I like this implementation proposal, but I've few r commendations:
- we don't need confit options for importers, we can bind importers into IOC and thus it's expandable and could be overridden easily too.
- the global entry point is fine for administration, but the main usage will be from the specific resource page from within the datatable just like export, and thus we can give certain permissions to users & have one interface for all actions per resource.
- would you elaborate more on the custom logic for assigning roles for example, so you've any ideas?
- I don't understand the last code block?!

**Comment by noxify** [comment]
Hi,

> would you elaborate more on the custom logic for assigning roles for example, so you've any ideas?

My idea for this is, when we're using the handler to manage the importing then we can do the same thing as it's already implemented in the app... example here is the seed command: 

https://github.com/rinvex/cortex-fort/blob/develop/src/Console/Commands/SeedCommand.php#L53-L76

In the handler, it's a simple loop... where we assign the fields for to the user fields and after creating the user record, we can assign the role to the user.

> I don't understand the last code block?!
The last two code blocks are just an example which I had it in my head :)
The first one, is the example from the docs. The second one is how I would implement it (with the config file).


If there are any questions or something is unknown, please let me know :)

**Comment by Omranic** [comment]
If we don't use config files for handlers, then I think we can use the first example as the docs says, right? I find it simpler, and we can acheive same results by by binding handlers into IoC as mentioned above, don't you agree?

**Comment by noxify** [comment]
Not sure if I understood it correctly - We will use different controllers instead of one generic controller. 

If this is correct - I'm fine with it, too.

**Comment by Omranic** [comment]
Hmmm, I gave it another thought and I like your approach. Just ignore my previous comments 😅

**Comment by noxify** [comment]
Ok - Which priority has this feature? Is it more important than the rinvex/fort features?

**Comment by Omranic** [comment]
Probably same priority, but could be considered higher now since `rivnex/fort` still has two features waiting review in pipeline.

**Comment by Omranic** [comment]
@noxify Thank you very much, I've implemented the **import** functionality in all [rinvex/cortex](https://github.com/rinvex/cortex) modules based on your work [noxify/cortex-importer](https://github.com/noxify/cortex-importer). I didn't merge it as a new module as I see it integral part of every module, so I added core support in [cortex/foundation](https://github.com/rinvex/cortex-foundation) then implemented it individually in a simpler way in every module. Your work was really inspiring in this task, so many thanks 😃 👍
